version: '3.8'
services:
  # Service de la base de données MySQL (inchangé)
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: demo_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Service de l'interface graphique PhpMyAdmin (NOUVEAU)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      # L'hôte (PMA_HOST) doit être le nom du service MySQL
      PMA_HOST: mysql-db 
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      # Vous pouvez aussi définir ici l'utilisateur/mot de passe par défaut
      # PMA_USER: root
      # PMA_PASSWORD: 1234
    links:
      - mysql-db:mysql-db
    restart: always
    ports:
      # Nous allons exposer phpMyAdmin sur le port 8081 pour éviter un conflit avec Spring Boot (8080)
      - '8081:80' 
    depends_on:
      - mysql-db

  # Service de l'application Spring Boot (inchangé)
  spring-app:
    image: ens/springdocker:1.0
    container_name: spring-app
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/demo_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

volumes:
  mysql-data: